import type { Metadata } from "next";
import { Smooch_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const smooch = Smooch_Sans({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: `Kara's Website`,
  description: "Generated by many tears wept",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${smooch.className} h-screen m-5`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
